In [0]:
import pandas as pd

In [0]:
pd.Series(range(3), index=pd.date_range('2019', freq='W', periods=3))

2019-01-06    0
2019-01-13    1
2019-01-20    2
Freq: W-SUN, dtype: int64

In [0]:
import datetime
import time


def getDateRangeFromWeek(p_year,p_week):

    firstdayofweek = datetime.datetime.strptime(f'{p_year}-W{int(p_week )- 1}-1', "%Y-W%W-%w").date()
    lastdayofweek = firstdayofweek + datetime.timedelta(days=6.9)
    return firstdayofweek, lastdayofweek


#Call function to get dates range 
firstdate, lastdate =  getDateRangeFromWeek('2019','2')

print('print function ',firstdate,' ', lastdate)

print function  2019-01-07   2019-01-13


In [0]:
import pandas as pd

In [0]:
df = pd.read_clipboard()

In [0]:
import torch

In [0]:
x = torch.rand(4,4)

In [0]:
x

tensor([[0.6268, 0.6237, 0.2305, 0.3261],
        [0.9008, 0.4655, 0.3386, 0.5053],
        [0.6954, 0.4162, 0.8014, 0.1855],
        [0.9082, 0.1367, 0.3515, 0.9641]])

In [0]:
y = x.view(16)

In [0]:
y

tensor([0.6268, 0.6237, 0.2305, 0.3261, 0.9008, 0.4655, 0.3386, 0.5053, 0.6954,
        0.4162, 0.8014, 0.1855, 0.9082, 0.1367, 0.3515, 0.9641])

In [0]:
y.shape

torch.Size([16])

In [0]:
x.shape

torch.Size([4, 4])

In [0]:
z = x.view(-1,8)

In [0]:
z

tensor([[0.6268, 0.6237, 0.2305, 0.3261, 0.9008, 0.4655, 0.3386, 0.5053],
        [0.6954, 0.4162, 0.8014, 0.1855, 0.9082, 0.1367, 0.3515, 0.9641]])

In [0]:
z.shape

torch.Size([2, 8])

In [0]:
x = torch.randn(1)

In [0]:
print(x)

tensor([1.7028])


In [0]:
print(x.item())

1.702815055847168


In [3]:
import numpy as np
seq_length = 1
time_stet = np.linespace(1, np.pi,seq_length + 1)

AttributeError: ignored

In [4]:
sudo python3.6 -m pip install -I numpy

SyntaxError: ignored